Fix/password requirements
bluewave-labs/bluewave-uptime pull request #1104
Opened 2024-10-31 19:15 UTC by marcelluscaio

- Adapted Check component to accept no highlighted text, avoiding code duplication
- Changed joi validation for password on Client and on Server, so they are validating on the same rules
- Deleted all validation done without the use of joi
- Created custom hook to keep validation of password and confirm in the same place
- Applied new architecture to SetNewPassword
- Broke Register Steps in different components (Step one two and three)
- Applied new architecture on Step Three
-  Applied new architecture on Login
- Applied new architecture on  Password Panel
- Adjusted styles on all of the pages

2024-11-01 02:19 UTC, ajhollid requested changes
Overall it looks great, I love the new feedback for users when setting up a password, much more informative and user friendly.

There's an issue with the Toasts that needs to be resovled, and I'm not sure of the reasoning for using the `props` prop for the `Button` components as it doesn't appear to expose that prop.

If I've missed something with regards to the `Button` let me know!

Other than that looks good to me!

2024-11-01 02:19 UTC, ajhollid commented on Client/src/Pages/Auth/Register/StepThree/index.jsx
> +						/>
This looks really great, I love the improvement here :+1:

2024-11-01 02:19 UTC, ajhollid commented on Client/src/Pages/Auth/Register/StepThree/index.jsx
> +								Object.keys(errors).length !== 0
Appreciate the strict evalutations here, not a big fan of JavaScripts type coercion

2024-11-01 02:19 UTC, ajhollid commented on Client/src/Pages/Auth/Register/StepOne/index.jsx
> +						props={{ tabIndex: -1 }}
As far as I can tell from [the docs](https://mui.com/material-ui/api/button/#props) the `Button` component doesn't expose `props` prop, nor does the `BaseButton` API :thinking:  It does expose `tabIndex` though, was there a reason not to use the `tabIndex` prop?

2024-11-01 02:19 UTC, ajhollid commented on Server/validation/joi.js
> +
Apprecaite the refactor here!

2024-11-01 10:01 UTC, marcelluscaio commented on Client/src/Validation/validation.js
> +			"string.empty": "empty",
Great point. The idea was not allowing submission while there were errors. But I also felt weird while using messages to cast error types. I'll look into that, and won't mix error type-casting and messages

2024-11-02 20:09 UTC, marcelluscaio commented on Client/src/Pages/Auth/Register/StepOne/index.jsx
> +						props={{ tabIndex: -1 }}
Solved!

2024-11-03 12:06 UTC, marcelluscaio commented
@ajhollid I think I addressed all of the problems. Most important, I was able to detach  joi's error type from message. Thank you again for your thorough review =D

2024-11-03 12:08 UTC, ajhollid commented
> @ajhollid I think I addressed all of the problems. Most important, I was able to detach  joi's error type from message. Thank you again for your thorough review =D

Awesome, nice work! I will review as soon as I can 🙏

2024-11-03 12:35 UTC, marcelluscaio commented
I updated the description by the way, Any doubt, let me know =)

2024-11-04 02:15 UTC, ajhollid approved these changes
Great work, everything looks good to me and is working as expected.

I really like being able to login/register without having to touch the mouse now :+1:

2024-11-04 02:15 UTC, ajhollid commented on Client/src/Validation/validation.js
> +		special: "Password must contain at least one special character",
Looking good :+1:  Nice work digging through the docs to figure this one out

2024-11-04 02:15 UTC, merged