Feat/fe/infrastrucutre area chart, resolves #1069
bluewave-labs/bluewave-uptime pull request #1159
Opened 2024-11-15 10:28 UTC by ajhollid

This PR suggests an implementation for an area chart that we can use for not only Infrasructure Monitors, but also to replace the Monitor Details chart.

- [x] Implement a reusable generic area chart
  - [x] Supports custom xAxis and yAxis ticks
  - [x] Supports gradient or solid background  
- [x] Add a Utils directory for commonly used chart utils
- [ ] Refactor MonitorDetails chart to use the generic chart - Probably to be done in a new PR

2024-11-15 10:32 UTC, ajhollid commented
There's some test data in a `data` file if anyone wants to try out the component.  It can be used as so:

```
import AreaChart from "../Components/Charts/AreaChart";
import data from "../Components/Charts/AreaChart/data.js";
import { useTheme } from "@mui/material";
import {
	TzTick,
	PercentTick,
	InfrastructureTooltip,
} from "../Components/Charts/Utils/chartUtils";

const Test = () => {
	const theme = useTheme();
	return (
		<AreaChart
			data={data}
			xTick={<TzTick />}
			yTick={<PercentTick />}
			xKey="createdAt"
			yKey="cpu.usage_percent"
			gradient={true}
			gradientStartColor={theme.palette.primary.main}
			gradientEndColor={theme.palette.primary.light}
			customTooltip={
				<InfrastructureTooltip
					dotColor={theme.palette.primary.main}
					yKey="cpu.usage_percent"
					yLabel="CPU usage percentage:"
				/>
			}
		/>
	);
};

export default Test;
```

2024-11-19 01:05 UTC, jennifer-gan requested changes
What is the index for?  if not used, maybe should remove it.

2024-11-19 17:52 UTC, jennifer-gan approved these changes

2024-11-20 05:59 UTC, ajhollid commented
This will be resolved in PR #1167

2024-11-20 05:59 UTC, closed without merging