Loading skeletons
bluewave-labs/bluewave-uptime pull request #564
Opened 2024-08-07 21:55 UTC by danielcj2

The PR may seem a tiny bit more intimidating than it actually is 😂 . A lot of the code was re-layered, which resulted in the high # of lines changed.

Resolves #550

2024-08-07 22:03 UTC, ajhollid requested changes
Scared me for a minute!

It looks fine to me, but I think it would be nice to extract those skeletons to their own components to keep the render method clean and readable.

If not possible / feasible let me know

2024-08-07 22:03 UTC, ajhollid commented on Client/src/Pages/Incidents/index.jsx
> +            <Skeleton variant="rounded" width="100%" height={100} />
Could the whole Skeleton be extracted to a component within the class? Just to keep the main render method a bit more readable

2024-08-07 22:03 UTC, ajhollid commented on Client/src/Pages/Monitors/Configure/index.jsx
> +              </>
Same for this one

2024-08-07 22:19 UTC, danielcj2 commented
> Scared me for a minute!
> 
> It looks fine to me, but I think it would be nice to extract those skeletons to their own components to keep the render method clean and readable.
> 
> If not possible / feasible let me know

It is definitely possible. We can have a folder with skeletons for each page. The reason why I didn't was because I had to use some arbitrary values to minimize the content shifting its position up and down, and I opted to leave the skeleton code beside the element that it is covering up in case we would need to make changes to the structure of the page. Also, it felt easier not worrying about positioning the skeletons since the base structure is done already 😛 

I'll work on refactoring the skeletons to their own components. Unfortunately, I don't think they'll be reusable since most our pages have different layouts.

2024-08-07 23:50 UTC, ajhollid commented
> > Scared me for a minute!
> > 
> > It looks fine to me, but I think it would be nice to extract those skeletons to their own components to keep the render method clean and readable.
> > 
> > If not possible / feasible let me know
> 
> It is definitely possible. We can have a folder with skeletons for each page. The reason why I didn't was because I had to use some arbitrary values to minimize the content shifting its position up and down, and I opted to leave the skeleton code beside the element that it is covering up in case we would need to make changes to the structure of the page. Also, it felt easier not worrying about positioning the skeletons since the base structure is done already 😛 
> 
> I'll work on refactoring the skeletons to their own components. Unfortunately, I don't think they'll be reusable since most our pages have different layouts.

No problem, I wasn't expecting they be reusable, just refactored for visibility.

Thanks for doing that!

2024-08-08 00:16 UTC, ajhollid approved these changes

2024-08-08 00:43 UTC, merged