fix: add css to fix the current password widget under account>password
bluewave-labs/bluewave-uptime pull request #940
Opened 2024-10-11 18:57 UTC by om-3004

##Fixes https://github.com/bluewave-labs/bluewave-uptime/issues/907 (Fix the "current password" widget)

- Added the CSS to fix current password widget in light/dark mode.
![Screenshot 2024-10-12 002318](https://github.com/user-attachments/assets/756e5c7d-861e-4a57-8c7b-dc78681a0f5e)
![Screenshot 2024-10-12 002329](https://github.com/user-attachments/assets/15ead897-2569-4198-84a2-2aff53cb584f)

2024-10-11 19:13 UTC, gorkem-bwl commented
Looks good, thanks!

2024-10-12 02:51 UTC, ajhollid requested changes
I understand what you are going for here and it works, however it isn't really maintainable.

I propose a different solution to this issue.

The root of the problem is that the `Field` component is meant to be hidden:

```
  <Field
    type="text"
    id="hidden-username"
    name="username"
    autoComplete="username"
    hidden={true}
    value=""
  />
```
      
however this is not behaving as expected.  The problem lies with the `Field` component and how the hidden prop is applied:
      
```
sx={
      type === "url"
        ? {
            "& .MuiInputBase-root": { padding: 0 },
            "& .MuiStack-root": {
              borderTopLeftRadius: theme.shape.borderRadius,
              borderBottomLeftRadius: theme.shape.borderRadius,
            },
          }
        : {
            display: hidden ? "none" : "",
          }
    }
```
          
The hidden prop is applied to the  `TextField` subcomponent of `Field`, while in fact it should be applied to the root `Stack` subcomponent of `Field`.

I suggest reverting `TextField`'s SX prop to

```
  sx={
    type === "url"
      ? {
          "& .MuiInputBase-root": { padding: 0 },
          "& .MuiStack-root": {
            borderTopLeftRadius: theme.shape.borderRadius,
            borderBottomLeftRadius: theme.shape.borderRadius,
          },
        }
      : {
        }
  } 
```
 and adding
 
 `display: hidden? "none" : ""`
 
 to the root `Stack` subcomponent.

2024-10-12 02:51 UTC, ajhollid commented on Client/src/Components/Sidebar/index.css
> +}
This is in the sidebar CSS file but it is targeting a field in the password panel component.  This is unmaintainable as future devs will not know this CSS is in this file, nor will they know what it is for if they come across this CSS in the future.

The specificity of this CSS selector is also not really maintainable as it is not reasonably possible to tell what that selector is for.  I assume it was extracted from dev tools inspector?  It works, but no one is going to know what it is for or what it means :thinking:

2024-10-12 08:26 UTC, om-3004 commented
@ajhollid Yes understood, you are right. I've committed that change so please review it.

2024-10-12 11:45 UTC, ajhollid approved these changes
Nice, short and sweet!  This resovles the issue, thank you for your contribution

2024-10-12 11:45 UTC, ajhollid commented on Client/src/Components/Inputs/Field/index.jsx
> +          display: hidden ? "none" : "",
Awesome, thanks for taking care of this :+1:

2024-10-12 11:45 UTC, merged