adds pause to action menu
bluewave-labs/bluewave-uptime pull request #945
Opened 2024-10-12 08:24 UTC by Sinon11901

This change resolves #931 by adding pause option in the actions menu on the dashboard.

2024-10-12 12:06 UTC, ajhollid requested changes
Looks great for the most part!  A couple of minor changes that I think clean things up a bit :+1:  Thanks for your hard work here!

2024-10-12 12:06 UTC, ajhollid commented on Client/src/Pages/Monitors/Home/actionsMenu.jsx
> +        throw new Error(action.error.message);
It's a good idea to safely access nested properties:

```
  throw new Error(action?.error?.message ?? "Failed to pause monitor.");
```

`action` isn't guaranteed to have `error` defined, so we shoudl fail gracefully if it isn't

2024-10-12 12:06 UTC, ajhollid commented on Client/src/Pages/Monitors/Home/actionsMenu.jsx
> +      console.error("Error pausing monitor:", monitor._id, error);
We have a utility Logger that we should use for logging:

```
  import { logger } from "../../../Utils/Logger";
  ...
  logger.error("Error pausing monitor:", monitor._id, error);
```

The logger was added mid-projecyt, so if you see `console.log` statements throughout the app we just haven't gotten around to replacing them yet.

2024-10-12 12:06 UTC, ajhollid commented on Client/src/Pages/Monitors/Home/actionsMenu.jsx
> +          )}
The regular braces are not needed here:

`{monitor?.isActive  === true ? "Pause" : "Resume"}`

is sufficient :+1:

2024-10-12 12:06 UTC, ajhollid commented on Client/src/Pages/Monitors/Home/actionsMenu.jsx
> +  const handlePause = async (event) => {
`event` parameter is unused, we can safely remove it

2024-10-12 12:06 UTC, ajhollid commented on Client/src/Pages/Monitors/Home/actionsMenu.jsx
> +        //window.location.reload();
We can remove this commented out code too

2024-10-13 01:54 UTC, ajhollid approved these changes
Looks good to me, thanks for making those changes :+1:

2024-10-13 01:55 UTC, merged

2024-10-13 07:34 UTC, Sinon11901 commented
Thank you for your cooperation and quick feedback. I really enjoyed working on this project.