Add link to logo
bluewave-labs/bluewave-uptime pull request #969
Opened 2024-10-15 15:52 UTC by khd33j

- [x] This PR adds a link to the logo

    - [x] Set an onClick() listener to the icon (BU) and 'BlueWave Uptime' 

    - [x] The [link](https://github.com/bluewave-labs/bluewave-uptime) opens up in a new tab as specified 

Let me know if I need to make further changes.

2024-10-15 15:53 UTC, gorkem-bwl commented
Can you make a video showing how it behaves when the sidebar is open and closed?

2024-10-15 15:56 UTC, khd33j commented
I don't really know how to run the app locally.

2024-10-15 15:59 UTC, gorkem-bwl commented
Make sure you test the code locally before sending a PR. 

https://bluewavelabs.gitbook.io/uptime-manager - here you can find the installation documentation.

2024-10-15 16:02 UTC, khd33j commented
Noted. I'll remember that for next time. 

I'm gonna reply with a video as soon as I install the app. 
Thanks for the feedback!

2024-10-15 23:45 UTC, ajhollid requested changes
Looks great!  We just need to add `cursor:pointer` to  the `Stack` so that the cusor behaves as if it were a link.

No need to close your PRs and make new ones when changes are requested, you can simply make the changes and push to your branch and your PR will be updated :smile: 

Thanks for your hard work!

2024-10-15 23:45 UTC, ajhollid commented on Client/src/Components/Sidebar/index.jsx
> +        <Stack direction="row" alignItems="center" gap={theme.spacing(4)} onClick={() => window.open("https://github.com/bluewave-labs/bluewave-uptime", "_blank", "noreferrer")}>
Can you add `sx={{ cursor: "pointer" }}` to this stack please?  That's the MUI way of declaring an inline style.

Thanks!

2024-10-16 09:41 UTC, khd33j commented
@ajhollid Okay, I'll add it in.

I didn't make the changes on a new branch. I used the develop branch itself. 
Figured it wouldn't matter since it is a small change. 

Can I still push it here or should I close the PR and push it in a new one?

2024-10-16 11:18 UTC, ajhollid commented
> @ajhollid Okay, I'll add it in.
> 
> I didn't make the changes on a new branch. I used the develop branch itself. 
> Figured it wouldn't matter since it is a small change. 
> 
> Can I still push it here or should I close the PR and push it in a new one?

Ah sorry I didn't notice that.

Yes please always create a new branch when implementing features, even if if they are small.

Thanks

2024-10-16 15:55 UTC, closed without merging